// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission.proto

package permission

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 权限
type Permission struct {
	PermissionId         string    `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id"`
	RoleId               string    `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id"`
	PermissionType       string    `protobuf:"bytes,3,opt,name=permission_type,json=permissionType,proto3" json:"permission_type"`
	AppId                string    `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id"`
	ActionType           string    `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type"`
	Actions              []*Action `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions"`
	CreatedAt            string    `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string    `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedAt            string    `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	UpdatedBy            string    `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{0}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetPermissionId() string {
	if m != nil {
		return m.PermissionId
	}
	return ""
}

func (m *Permission) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *Permission) GetPermissionType() string {
	if m != nil {
		return m.PermissionType
	}
	return ""
}

func (m *Permission) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Permission) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *Permission) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Permission) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Permission) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Permission) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Permission) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type Action struct {
	ObjectId             string          `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id"`
	Fields               []string        `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields"`
	ActionMap            map[string]bool `protobuf:"bytes,3,rep,name=action_map,json=actionMap,proto3" json:"action_map" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	RoleName             string          `protobuf:"bytes,4,opt,name=role_name,json=roleName,proto3" json:"role_name"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{1}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Action) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Action) GetActionMap() map[string]bool {
	if m != nil {
		return m.ActionMap
	}
	return nil
}

func (m *Action) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type FindActionsRequest struct {
	RoleId               []string `protobuf:"bytes,1,rep,name=role_id,json=roleId,proto3" json:"role_id"`
	PermissionType       string   `protobuf:"bytes,2,opt,name=permission_type,json=permissionType,proto3" json:"permission_type"`
	AppId                string   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id"`
	ActionType           string   `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type"`
	ObjectId             string   `protobuf:"bytes,5,opt,name=object_id,json=objectId,proto3" json:"object_id"`
	Database             string   `protobuf:"bytes,6,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindActionsRequest) Reset()         { *m = FindActionsRequest{} }
func (m *FindActionsRequest) String() string { return proto.CompactTextString(m) }
func (*FindActionsRequest) ProtoMessage()    {}
func (*FindActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{2}
}

func (m *FindActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindActionsRequest.Unmarshal(m, b)
}
func (m *FindActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindActionsRequest.Marshal(b, m, deterministic)
}
func (m *FindActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindActionsRequest.Merge(m, src)
}
func (m *FindActionsRequest) XXX_Size() int {
	return xxx_messageInfo_FindActionsRequest.Size(m)
}
func (m *FindActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindActionsRequest proto.InternalMessageInfo

func (m *FindActionsRequest) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *FindActionsRequest) GetPermissionType() string {
	if m != nil {
		return m.PermissionType
	}
	return ""
}

func (m *FindActionsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FindActionsRequest) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *FindActionsRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *FindActionsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindActionsResponse struct {
	Actions              []*Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindActionsResponse) Reset()         { *m = FindActionsResponse{} }
func (m *FindActionsResponse) String() string { return proto.CompactTextString(m) }
func (*FindActionsResponse) ProtoMessage()    {}
func (*FindActionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{3}
}

func (m *FindActionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindActionsResponse.Unmarshal(m, b)
}
func (m *FindActionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindActionsResponse.Marshal(b, m, deterministic)
}
func (m *FindActionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindActionsResponse.Merge(m, src)
}
func (m *FindActionsResponse) XXX_Size() int {
	return xxx_messageInfo_FindActionsResponse.Size(m)
}
func (m *FindActionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindActionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindActionsResponse proto.InternalMessageInfo

func (m *FindActionsResponse) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type FindPermissionsRequest struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindPermissionsRequest) Reset()         { *m = FindPermissionsRequest{} }
func (m *FindPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*FindPermissionsRequest) ProtoMessage()    {}
func (*FindPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{4}
}

func (m *FindPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPermissionsRequest.Unmarshal(m, b)
}
func (m *FindPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPermissionsRequest.Marshal(b, m, deterministic)
}
func (m *FindPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPermissionsRequest.Merge(m, src)
}
func (m *FindPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_FindPermissionsRequest.Size(m)
}
func (m *FindPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindPermissionsRequest proto.InternalMessageInfo

func (m *FindPermissionsRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *FindPermissionsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindPermissionsResponse struct {
	Permission           []*Permission `protobuf:"bytes,1,rep,name=permission,proto3" json:"permission"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FindPermissionsResponse) Reset()         { *m = FindPermissionsResponse{} }
func (m *FindPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*FindPermissionsResponse) ProtoMessage()    {}
func (*FindPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{5}
}

func (m *FindPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPermissionsResponse.Unmarshal(m, b)
}
func (m *FindPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPermissionsResponse.Marshal(b, m, deterministic)
}
func (m *FindPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPermissionsResponse.Merge(m, src)
}
func (m *FindPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_FindPermissionsResponse.Size(m)
}
func (m *FindPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindPermissionsResponse proto.InternalMessageInfo

func (m *FindPermissionsResponse) GetPermission() []*Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

func init() {
	proto.RegisterType((*Permission)(nil), "permission.Permission")
	proto.RegisterType((*Action)(nil), "permission.Action")
	proto.RegisterMapType((map[string]bool)(nil), "permission.Action.ActionMapEntry")
	proto.RegisterType((*FindActionsRequest)(nil), "permission.FindActionsRequest")
	proto.RegisterType((*FindActionsResponse)(nil), "permission.FindActionsResponse")
	proto.RegisterType((*FindPermissionsRequest)(nil), "permission.FindPermissionsRequest")
	proto.RegisterType((*FindPermissionsResponse)(nil), "permission.FindPermissionsResponse")
}

func init() { proto.RegisterFile("permission.proto", fileDescriptor_c837ef01cbda0ad8) }

var fileDescriptor_c837ef01cbda0ad8 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x76, 0xe3, 0xd8, 0x13, 0x68, 0xcb, 0x00, 0xa9, 0x15, 0x04, 0x0d, 0xee, 0x81, 0x1e,
	0x50, 0x0f, 0x45, 0x42, 0x08, 0x71, 0xa0, 0x45, 0x20, 0xe5, 0x50, 0x54, 0x0c, 0x47, 0xa4, 0x68,
	0x9d, 0x5d, 0x24, 0x43, 0x62, 0x2f, 0xde, 0x4d, 0x25, 0xff, 0x3e, 0x0e, 0xfc, 0x02, 0x2e, 0xfc,
	0x1a, 0xb4, 0xbb, 0x76, 0xbd, 0x8e, 0xfb, 0x71, 0xb2, 0xe7, 0xbd, 0x79, 0xe3, 0x37, 0xb3, 0xb3,
	0x86, 0x5d, 0xce, 0xca, 0x55, 0x26, 0x44, 0x56, 0xe4, 0x47, 0xbc, 0x2c, 0x64, 0x81, 0xd0, 0x22,
	0xf1, 0x5f, 0x17, 0xe0, 0xfc, 0x32, 0xc4, 0x03, 0xb8, 0xd7, 0x92, 0xf3, 0x8c, 0x46, 0xce, 0xd4,
	0x39, 0x0c, 0x93, 0xbb, 0x2d, 0x38, 0xa3, 0xb8, 0x07, 0xc3, 0xb2, 0x58, 0x32, 0x45, 0xbb, 0x9a,
	0xf6, 0x55, 0x38, 0xa3, 0xf8, 0x1c, 0x76, 0x2c, 0xb5, 0xac, 0x38, 0x8b, 0x3c, 0x9d, 0xb0, 0xdd,
	0xc2, 0x5f, 0x2b, 0xce, 0xf0, 0x11, 0xf8, 0x84, 0x73, 0x55, 0x60, 0x4b, 0xf3, 0x03, 0xc2, 0xf9,
	0x8c, 0xe2, 0x3e, 0x8c, 0xc8, 0x42, 0x5e, 0x6a, 0x07, 0x9a, 0x03, 0x03, 0x69, 0xdd, 0x0b, 0x18,
	0x9a, 0x48, 0x44, 0xfe, 0xd4, 0x3b, 0x1c, 0x1d, 0xe3, 0x91, 0xd5, 0xdd, 0x89, 0xa6, 0x92, 0x26,
	0x05, 0x9f, 0x00, 0x2c, 0x4a, 0x46, 0x24, 0xa3, 0x73, 0x22, 0xa3, 0xa1, 0xae, 0x16, 0xd6, 0xc8,
	0x89, 0xb4, 0xe9, 0xb4, 0x8a, 0x82, 0x0e, 0x7d, 0x5a, 0x29, 0x7a, 0xcd, 0x69, 0xa3, 0x0e, 0x0d,
	0x5d, 0x23, 0x46, 0xdd, 0xd0, 0x69, 0x15, 0x41, 0x87, 0x3e, 0xad, 0xe2, 0x7f, 0x0e, 0xf8, 0xc6,
	0x0f, 0x3e, 0x86, 0xb0, 0x48, 0x7f, 0xb0, 0x85, 0x6c, 0xe7, 0x19, 0x18, 0x60, 0x46, 0x71, 0x0c,
	0xfe, 0xf7, 0x8c, 0x2d, 0xa9, 0x88, 0xdc, 0xa9, 0xa7, 0x46, 0x69, 0x22, 0x7c, 0x07, 0x75, 0xdf,
	0xf3, 0x15, 0xe1, 0x91, 0xa7, 0x9b, 0x7d, 0xd6, 0x6f, 0xb6, 0x7e, 0x9c, 0x11, 0xfe, 0x21, 0x97,
	0x65, 0x95, 0x84, 0xa4, 0x89, 0xd5, 0x67, 0xf5, 0x29, 0xe5, 0x64, 0xc5, 0xea, 0x31, 0x07, 0x0a,
	0xf8, 0x44, 0x56, 0x6c, 0xf2, 0x16, 0xb6, 0xbb, 0x4a, 0xdc, 0x05, 0xef, 0x27, 0xab, 0x6a, 0x7f,
	0xea, 0x15, 0x1f, 0xc2, 0xe0, 0x82, 0x2c, 0xd7, 0x4c, 0x1f, 0x72, 0x90, 0x98, 0xe0, 0x8d, 0xfb,
	0xda, 0x89, 0xff, 0x38, 0x80, 0x1f, 0xb3, 0x9c, 0x9a, 0x12, 0x22, 0x61, 0xbf, 0xd6, 0x4c, 0x48,
	0x7b, 0x2f, 0x1c, 0xd3, 0xcc, 0xf5, 0x7b, 0xe1, 0xde, 0xb2, 0x17, 0xde, 0x0d, 0x7b, 0xb1, 0xd5,
	0xdb, 0x8b, 0xce, 0x88, 0x07, 0x1b, 0x23, 0x9e, 0x40, 0x40, 0x89, 0x24, 0x29, 0x11, 0x2c, 0xf2,
	0x0d, 0xd7, 0xc4, 0xf1, 0x7b, 0x78, 0xd0, 0x69, 0x44, 0xf0, 0x22, 0x17, 0x9d, 0x3d, 0x73, 0x6e,
	0xdd, 0xb3, 0xf8, 0x0c, 0xc6, 0xaa, 0x48, 0x7b, 0x8d, 0xae, 0x9e, 0x88, 0x7d, 0x53, 0x6c, 0x4f,
	0xee, 0x86, 0xa7, 0xcf, 0xb0, 0xd7, 0x2b, 0x57, 0xfb, 0x7a, 0x05, 0xd6, 0xdd, 0xad, 0xad, 0x8d,
	0x6d, 0x6b, 0xad, 0x28, 0xb1, 0x32, 0x8f, 0x7f, 0x3b, 0x70, 0xbf, 0xa5, 0xbe, 0xb0, 0xf2, 0x22,
	0x5b, 0x30, 0x3c, 0x87, 0x91, 0xd5, 0x3c, 0x3e, 0xb5, 0x0b, 0xf5, 0x8f, 0x77, 0xb2, 0x7f, 0x2d,
	0x6f, 0xdc, 0xc5, 0x77, 0xf0, 0x1b, 0xec, 0x6c, 0x58, 0xc7, 0x78, 0x53, 0xd5, 0x1f, 0xd3, 0xe4,
	0xe0, 0xc6, 0x9c, 0xa6, 0x7a, 0xea, 0xeb, 0xdf, 0xd7, 0xcb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x26, 0x61, 0x64, 0x3c, 0xd2, 0x04, 0x00, 0x00,
}
