// Code generated by protoc-gen-go. DO NOT EDIT.
// source: upload.proto

package upload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 基础参数
type Params struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action"`
	Encoding             string   `protobuf:"bytes,3,opt,name=encoding,proto3" json:"encoding"`
	ZipCharset           string   `protobuf:"bytes,16,opt,name=zip_charset,json=zipCharset,proto3" json:"zip_charset"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id"`
	AppId                string   `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Lang                 string   `protobuf:"bytes,6,opt,name=lang,proto3" json:"lang"`
	Domain               string   `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain"`
	DatastoreId          string   `protobuf:"bytes,8,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	GroupId              string   `protobuf:"bytes,11,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	EmptyChange          bool     `protobuf:"varint,17,opt,name=empty_change,json=emptyChange,proto3" json:"empty_change"`
	AccessKeys           []string `protobuf:"bytes,12,rep,name=access_keys,json=accessKeys,proto3" json:"access_keys"`
	Owners               []string `protobuf:"bytes,13,rep,name=owners,proto3" json:"owners"`
	Roles                []string `protobuf:"bytes,14,rep,name=roles,proto3" json:"roles"`
	WfId                 string   `protobuf:"bytes,15,opt,name=wf_id,json=wfId,proto3" json:"wf_id"`
	Database             string   `protobuf:"bytes,10,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{0}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Params) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Params) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *Params) GetZipCharset() string {
	if m != nil {
		return m.ZipCharset
	}
	return ""
}

func (m *Params) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Params) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Params) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Params) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Params) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *Params) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *Params) GetEmptyChange() bool {
	if m != nil {
		return m.EmptyChange
	}
	return false
}

func (m *Params) GetAccessKeys() []string {
	if m != nil {
		return m.AccessKeys
	}
	return nil
}

func (m *Params) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *Params) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Params) GetWfId() string {
	if m != nil {
		return m.WfId
	}
	return ""
}

func (m *Params) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

// 文件参数
type FileParams struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path"`
	ZipFilePath          string   `protobuf:"bytes,2,opt,name=zip_file_path,json=zipFilePath,proto3" json:"zip_file_path"`
	PayFilePath          string   `protobuf:"bytes,3,opt,name=pay_file_path,json=payFilePath,proto3" json:"pay_file_path"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileParams) Reset()         { *m = FileParams{} }
func (m *FileParams) String() string { return proto.CompactTextString(m) }
func (*FileParams) ProtoMessage()    {}
func (*FileParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{1}
}

func (m *FileParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileParams.Unmarshal(m, b)
}
func (m *FileParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileParams.Marshal(b, m, deterministic)
}
func (m *FileParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileParams.Merge(m, src)
}
func (m *FileParams) XXX_Size() int {
	return xxx_messageInfo_FileParams.Size(m)
}
func (m *FileParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FileParams.DiscardUnknown(m)
}

var xxx_messageInfo_FileParams proto.InternalMessageInfo

func (m *FileParams) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *FileParams) GetZipFilePath() string {
	if m != nil {
		return m.ZipFilePath
	}
	return ""
}

func (m *FileParams) GetPayFilePath() string {
	if m != nil {
		return m.PayFilePath
	}
	return ""
}

type CSVRequest struct {
	BaseParams           *Params     `protobuf:"bytes,1,opt,name=base_params,json=baseParams,proto3" json:"base_params"`
	FileParams           *FileParams `protobuf:"bytes,2,opt,name=file_params,json=fileParams,proto3" json:"file_params"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CSVRequest) Reset()         { *m = CSVRequest{} }
func (m *CSVRequest) String() string { return proto.CompactTextString(m) }
func (*CSVRequest) ProtoMessage()    {}
func (*CSVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{2}
}

func (m *CSVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVRequest.Unmarshal(m, b)
}
func (m *CSVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVRequest.Marshal(b, m, deterministic)
}
func (m *CSVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVRequest.Merge(m, src)
}
func (m *CSVRequest) XXX_Size() int {
	return xxx_messageInfo_CSVRequest.Size(m)
}
func (m *CSVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CSVRequest proto.InternalMessageInfo

func (m *CSVRequest) GetBaseParams() *Params {
	if m != nil {
		return m.BaseParams
	}
	return nil
}

func (m *CSVRequest) GetFileParams() *FileParams {
	if m != nil {
		return m.FileParams
	}
	return nil
}

type CSVResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSVResponse) Reset()         { *m = CSVResponse{} }
func (m *CSVResponse) String() string { return proto.CompactTextString(m) }
func (*CSVResponse) ProtoMessage()    {}
func (*CSVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{3}
}

func (m *CSVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVResponse.Unmarshal(m, b)
}
func (m *CSVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVResponse.Marshal(b, m, deterministic)
}
func (m *CSVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVResponse.Merge(m, src)
}
func (m *CSVResponse) XXX_Size() int {
	return xxx_messageInfo_CSVResponse.Size(m)
}
func (m *CSVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CSVResponse proto.InternalMessageInfo

// 批量盘点基础参数
type CheckParams struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id"`
	Encoding             string   `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id"`
	AppId                string   `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Lang                 string   `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang"`
	Domain               string   `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain"`
	DatastoreId          string   `protobuf:"bytes,7,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	GroupId              string   `protobuf:"bytes,8,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	AccessKeys           []string `protobuf:"bytes,9,rep,name=access_keys,json=accessKeys,proto3" json:"access_keys"`
	Owners               []string `protobuf:"bytes,10,rep,name=owners,proto3" json:"owners"`
	Roles                []string `protobuf:"bytes,11,rep,name=roles,proto3" json:"roles"`
	Database             string   `protobuf:"bytes,12,opt,name=database,proto3" json:"database"`
	MainKeys             []string `protobuf:"bytes,13,rep,name=main_keys,json=mainKeys,proto3" json:"main_keys"`
	CheckType            string   `protobuf:"bytes,14,opt,name=check_type,json=checkType,proto3" json:"check_type"`
	CheckedAt            string   `protobuf:"bytes,15,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at"`
	CheckedBy            string   `protobuf:"bytes,16,opt,name=checked_by,json=checkedBy,proto3" json:"checked_by"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckParams) Reset()         { *m = CheckParams{} }
func (m *CheckParams) String() string { return proto.CompactTextString(m) }
func (*CheckParams) ProtoMessage()    {}
func (*CheckParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{4}
}

func (m *CheckParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckParams.Unmarshal(m, b)
}
func (m *CheckParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckParams.Marshal(b, m, deterministic)
}
func (m *CheckParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckParams.Merge(m, src)
}
func (m *CheckParams) XXX_Size() int {
	return xxx_messageInfo_CheckParams.Size(m)
}
func (m *CheckParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckParams.DiscardUnknown(m)
}

var xxx_messageInfo_CheckParams proto.InternalMessageInfo

func (m *CheckParams) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *CheckParams) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *CheckParams) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CheckParams) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CheckParams) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *CheckParams) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CheckParams) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *CheckParams) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *CheckParams) GetAccessKeys() []string {
	if m != nil {
		return m.AccessKeys
	}
	return nil
}

func (m *CheckParams) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *CheckParams) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *CheckParams) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *CheckParams) GetMainKeys() []string {
	if m != nil {
		return m.MainKeys
	}
	return nil
}

func (m *CheckParams) GetCheckType() string {
	if m != nil {
		return m.CheckType
	}
	return ""
}

func (m *CheckParams) GetCheckedAt() string {
	if m != nil {
		return m.CheckedAt
	}
	return ""
}

func (m *CheckParams) GetCheckedBy() string {
	if m != nil {
		return m.CheckedBy
	}
	return ""
}

type InventoryRequest struct {
	BaseParams           *CheckParams `protobuf:"bytes,1,opt,name=base_params,json=baseParams,proto3" json:"base_params"`
	FilePath             string       `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InventoryRequest) Reset()         { *m = InventoryRequest{} }
func (m *InventoryRequest) String() string { return proto.CompactTextString(m) }
func (*InventoryRequest) ProtoMessage()    {}
func (*InventoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{5}
}

func (m *InventoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryRequest.Unmarshal(m, b)
}
func (m *InventoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryRequest.Marshal(b, m, deterministic)
}
func (m *InventoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryRequest.Merge(m, src)
}
func (m *InventoryRequest) XXX_Size() int {
	return xxx_messageInfo_InventoryRequest.Size(m)
}
func (m *InventoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryRequest proto.InternalMessageInfo

func (m *InventoryRequest) GetBaseParams() *CheckParams {
	if m != nil {
		return m.BaseParams
	}
	return nil
}

func (m *InventoryRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type InventoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryResponse) Reset()         { *m = InventoryResponse{} }
func (m *InventoryResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryResponse) ProtoMessage()    {}
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{6}
}

func (m *InventoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryResponse.Unmarshal(m, b)
}
func (m *InventoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryResponse.Marshal(b, m, deterministic)
}
func (m *InventoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryResponse.Merge(m, src)
}
func (m *InventoryResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryResponse.Size(m)
}
func (m *InventoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryResponse proto.InternalMessageInfo

// 基础参数
type MappingParams struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id"`
	MappingId            string   `protobuf:"bytes,2,opt,name=mapping_id,json=mappingId,proto3" json:"mapping_id"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id"`
	AppId                string   `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Lang                 string   `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang"`
	Domain               string   `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain"`
	DatastoreId          string   `protobuf:"bytes,7,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	EmptyChange          bool     `protobuf:"varint,12,opt,name=empty_change,json=emptyChange,proto3" json:"empty_change"`
	AccessKeys           []string `protobuf:"bytes,8,rep,name=access_keys,json=accessKeys,proto3" json:"access_keys"`
	Owners               []string `protobuf:"bytes,9,rep,name=owners,proto3" json:"owners"`
	Roles                []string `protobuf:"bytes,10,rep,name=roles,proto3" json:"roles"`
	Database             string   `protobuf:"bytes,11,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MappingParams) Reset()         { *m = MappingParams{} }
func (m *MappingParams) String() string { return proto.CompactTextString(m) }
func (*MappingParams) ProtoMessage()    {}
func (*MappingParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{7}
}

func (m *MappingParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MappingParams.Unmarshal(m, b)
}
func (m *MappingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MappingParams.Marshal(b, m, deterministic)
}
func (m *MappingParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MappingParams.Merge(m, src)
}
func (m *MappingParams) XXX_Size() int {
	return xxx_messageInfo_MappingParams.Size(m)
}
func (m *MappingParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MappingParams.DiscardUnknown(m)
}

var xxx_messageInfo_MappingParams proto.InternalMessageInfo

func (m *MappingParams) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *MappingParams) GetMappingId() string {
	if m != nil {
		return m.MappingId
	}
	return ""
}

func (m *MappingParams) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MappingParams) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *MappingParams) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *MappingParams) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *MappingParams) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *MappingParams) GetEmptyChange() bool {
	if m != nil {
		return m.EmptyChange
	}
	return false
}

func (m *MappingParams) GetAccessKeys() []string {
	if m != nil {
		return m.AccessKeys
	}
	return nil
}

func (m *MappingParams) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *MappingParams) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *MappingParams) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type MappingRequest struct {
	BaseParams           *MappingParams `protobuf:"bytes,1,opt,name=base_params,json=baseParams,proto3" json:"base_params"`
	FilePath             string         `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MappingRequest) Reset()         { *m = MappingRequest{} }
func (m *MappingRequest) String() string { return proto.CompactTextString(m) }
func (*MappingRequest) ProtoMessage()    {}
func (*MappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{8}
}

func (m *MappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MappingRequest.Unmarshal(m, b)
}
func (m *MappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MappingRequest.Marshal(b, m, deterministic)
}
func (m *MappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MappingRequest.Merge(m, src)
}
func (m *MappingRequest) XXX_Size() int {
	return xxx_messageInfo_MappingRequest.Size(m)
}
func (m *MappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MappingRequest proto.InternalMessageInfo

func (m *MappingRequest) GetBaseParams() *MappingParams {
	if m != nil {
		return m.BaseParams
	}
	return nil
}

func (m *MappingRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type MappingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MappingResponse) Reset()         { *m = MappingResponse{} }
func (m *MappingResponse) String() string { return proto.CompactTextString(m) }
func (*MappingResponse) ProtoMessage()    {}
func (*MappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{9}
}

func (m *MappingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MappingResponse.Unmarshal(m, b)
}
func (m *MappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MappingResponse.Marshal(b, m, deterministic)
}
func (m *MappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MappingResponse.Merge(m, src)
}
func (m *MappingResponse) XXX_Size() int {
	return xxx_messageInfo_MappingResponse.Size(m)
}
func (m *MappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MappingResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "upload.Params")
	proto.RegisterType((*FileParams)(nil), "upload.FileParams")
	proto.RegisterType((*CSVRequest)(nil), "upload.CSVRequest")
	proto.RegisterType((*CSVResponse)(nil), "upload.CSVResponse")
	proto.RegisterType((*CheckParams)(nil), "upload.CheckParams")
	proto.RegisterType((*InventoryRequest)(nil), "upload.InventoryRequest")
	proto.RegisterType((*InventoryResponse)(nil), "upload.InventoryResponse")
	proto.RegisterType((*MappingParams)(nil), "upload.MappingParams")
	proto.RegisterType((*MappingRequest)(nil), "upload.MappingRequest")
	proto.RegisterType((*MappingResponse)(nil), "upload.MappingResponse")
}

func init() { proto.RegisterFile("upload.proto", fileDescriptor_91b94b655bd2a7e5) }

var fileDescriptor_91b94b655bd2a7e5 = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0xdf, 0x4e, 0xdb, 0x3e,
	0x14, 0xc7, 0x7f, 0x6d, 0x69, 0x9a, 0x9c, 0xb4, 0x05, 0xdc, 0x1f, 0x10, 0x98, 0xd0, 0x58, 0xae,
	0xb8, 0x62, 0x12, 0x4c, 0xdc, 0x8f, 0x4a, 0x68, 0xd1, 0x34, 0x69, 0x2a, 0x1b, 0xb7, 0x91, 0x9b,
	0xb8, 0x6d, 0xa0, 0x8d, 0x4d, 0x9c, 0x82, 0xc2, 0x5b, 0xed, 0x09, 0xf6, 0x0e, 0x93, 0xf6, 0x3e,
	0x93, 0xff, 0x24, 0x4d, 0xba, 0xd0, 0xed, 0x6e, 0x77, 0x39, 0xdf, 0x63, 0x9f, 0x73, 0xec, 0xef,
	0xa7, 0x2e, 0x74, 0x97, 0x6c, 0x4e, 0x71, 0x78, 0xc6, 0x12, 0x9a, 0x52, 0x64, 0xa8, 0xc8, 0xfd,
	0xd6, 0x02, 0xe3, 0x33, 0x4e, 0xf0, 0x82, 0xa3, 0x3d, 0x30, 0xee, 0xe8, 0xd8, 0x8f, 0x42, 0xa7,
	0x71, 0xd2, 0x38, 0xb5, 0x46, 0xed, 0x3b, 0x3a, 0xf6, 0x42, 0xb4, 0x0f, 0x06, 0x0e, 0xd2, 0x88,
	0xc6, 0x4e, 0x53, 0xca, 0x3a, 0x42, 0x47, 0x60, 0x92, 0x38, 0xa0, 0x61, 0x14, 0x4f, 0x9d, 0x96,
	0xcc, 0x14, 0x31, 0x7a, 0x0d, 0xf6, 0x73, 0xc4, 0xfc, 0x60, 0x86, 0x13, 0x4e, 0x52, 0x67, 0x47,
	0xa6, 0xe1, 0x39, 0x62, 0x43, 0xa5, 0xa0, 0x03, 0xe8, 0x2c, 0x39, 0x49, 0x44, 0xb3, 0x2d, 0x55,
	0x55, 0x84, 0x5e, 0x28, 0x86, 0xc0, 0x8c, 0x09, 0xbd, 0xad, 0x86, 0xc0, 0x8c, 0x79, 0x21, 0x42,
	0xb0, 0x35, 0xc7, 0xf1, 0xd4, 0x31, 0xa4, 0x28, 0xbf, 0xc5, 0x60, 0x21, 0x5d, 0xe0, 0x28, 0x76,
	0x3a, 0xaa, 0x84, 0x8a, 0xd0, 0x1b, 0xe8, 0x86, 0x38, 0xc5, 0x3c, 0xa5, 0x09, 0x11, 0x85, 0x4c,
	0x99, 0xb5, 0x0b, 0xcd, 0x0b, 0xd1, 0x21, 0x98, 0xd3, 0x84, 0x2e, 0x65, 0x1f, 0x5b, 0xa6, 0x3b,
	0x32, 0xf6, 0x42, 0xb1, 0x9b, 0x2c, 0x58, 0x9a, 0x89, 0xe1, 0xe3, 0x29, 0x71, 0x76, 0x4f, 0x1a,
	0xa7, 0xe6, 0xc8, 0x96, 0xda, 0x50, 0x4a, 0xe2, 0x74, 0x38, 0x08, 0x08, 0xe7, 0xfe, 0x3d, 0xc9,
	0xb8, 0xd3, 0x3d, 0x69, 0x89, 0xd3, 0x29, 0xe9, 0x23, 0xc9, 0xb8, 0x98, 0x8c, 0x3e, 0xc5, 0x24,
	0xe1, 0x4e, 0x4f, 0xe6, 0x74, 0x84, 0xfe, 0x87, 0x76, 0x42, 0xe7, 0x84, 0x3b, 0x7d, 0x29, 0xab,
	0x00, 0x0d, 0xa0, 0xfd, 0x34, 0x11, 0x93, 0x6c, 0xab, 0xc3, 0x3d, 0x4d, 0xbc, 0x50, 0xdc, 0xae,
	0x18, 0x78, 0x8c, 0x39, 0x71, 0x40, 0xdd, 0x6e, 0x1e, 0xbb, 0x0f, 0x00, 0xd7, 0xd1, 0x9c, 0x68,
	0xdb, 0x5e, 0x81, 0x35, 0x89, 0xe6, 0xc4, 0x67, 0x38, 0x9d, 0x69, 0xe7, 0xcc, 0x89, 0x4c, 0xa7,
	0x33, 0xe4, 0x42, 0x4f, 0x18, 0xb1, 0x5a, 0xa0, 0x3c, 0x14, 0xee, 0x5c, 0x97, 0xd6, 0x30, 0x9c,
	0x95, 0xd6, 0x28, 0x37, 0x6d, 0x86, 0xb3, 0x7c, 0x8d, 0x9b, 0x00, 0x0c, 0x6f, 0x6e, 0x47, 0xe4,
	0x61, 0x49, 0x78, 0x8a, 0xde, 0x82, 0x2d, 0x06, 0xf1, 0x99, 0x9c, 0x40, 0x36, 0xb5, 0xcf, 0xfb,
	0x67, 0x1a, 0x30, 0x35, 0xd7, 0x08, 0xc4, 0x12, 0x3d, 0xe3, 0x05, 0xd8, 0xba, 0xbc, 0xdc, 0xd0,
	0x94, 0x1b, 0x50, 0xbe, 0x61, 0x75, 0x98, 0x11, 0x4c, 0x8a, 0x6f, 0xb7, 0x07, 0xb6, 0xec, 0xc9,
	0x19, 0x8d, 0x39, 0x71, 0xbf, 0xb7, 0xc0, 0x1e, 0xce, 0x48, 0x70, 0xbf, 0x19, 0xd7, 0x32, 0x96,
	0xcd, 0x35, 0x2c, 0x4b, 0xd4, 0xb5, 0x5e, 0xa0, 0x6e, 0xab, 0x8e, 0xba, 0x76, 0x2d, 0x75, 0xc6,
	0x46, 0xea, 0x3a, 0x9b, 0xa9, 0x33, 0xab, 0xd4, 0xad, 0x21, 0x65, 0x6d, 0x40, 0x0a, 0xea, 0x91,
	0xb2, 0xcb, 0x48, 0x95, 0xe9, 0xe9, 0x56, 0xe9, 0x11, 0xbc, 0x88, 0x81, 0x55, 0x23, 0xc5, 0xa7,
	0x29, 0x04, 0xd9, 0xe6, 0x18, 0x20, 0x10, 0x77, 0xec, 0xa7, 0x19, 0x23, 0x4e, 0x5f, 0x6e, 0xb5,
	0xa4, 0xf2, 0x25, 0x63, 0xa4, 0x48, 0x93, 0xd0, 0xc7, 0xa9, 0xe6, 0xd5, 0xd2, 0xca, 0xfb, 0xb4,
	0x9c, 0x1e, 0x67, 0xfa, 0x57, 0x9f, 0xa7, 0xaf, 0x32, 0x97, 0xc0, 0x8e, 0x17, 0x3f, 0x92, 0x38,
	0xa5, 0x49, 0x96, 0xa3, 0xf4, 0xae, 0x0e, 0xa5, 0x41, 0x4e, 0x46, 0xc9, 0xef, 0x0a, 0x4f, 0x15,
	0xe6, 0x9b, 0x55, 0xe6, 0xdd, 0x01, 0xec, 0x96, 0xda, 0x68, 0x7a, 0x7e, 0x34, 0xa1, 0xf7, 0x09,
	0x33, 0x16, 0xc5, 0xd3, 0xcd, 0xfc, 0x1c, 0x03, 0x2c, 0xd4, 0x3a, 0x91, 0x52, 0xb5, 0x2d, 0xad,
	0x78, 0xe1, 0xbf, 0x46, 0x68, 0xfd, 0x75, 0xea, 0xfe, 0xf1, 0x75, 0x32, 0x37, 0xa0, 0x64, 0xd5,
	0xa3, 0x04, 0x2f, 0xa1, 0x64, 0xaf, 0x3d, 0x44, 0x04, 0xfa, 0xfa, 0x4e, 0x73, 0x3b, 0x2f, 0xeb,
	0xec, 0xdc, 0xcb, 0xed, 0xac, 0x18, 0xf0, 0xf7, 0x86, 0xee, 0xc2, 0x76, 0xd1, 0x46, 0xd9, 0x79,
	0xfe, 0xb3, 0x01, 0xbd, 0xaf, 0xb2, 0xe8, 0x0d, 0x49, 0x1e, 0xa3, 0x80, 0xa0, 0x4b, 0xb0, 0x86,
	0x37, 0xb7, 0x4a, 0x43, 0xc5, 0xd3, 0xb2, 0x7a, 0xb4, 0x8e, 0x06, 0x15, 0x4d, 0x63, 0xf1, 0x1f,
	0xfa, 0x00, 0xdb, 0x05, 0x2d, 0x7a, 0xb7, 0x93, 0xaf, 0x5c, 0xa7, 0xf5, 0xe8, 0xb0, 0x26, 0x53,
	0x54, 0xba, 0x2a, 0x08, 0xd3, 0x75, 0xf6, 0xd7, 0xce, 0x9d, 0x57, 0x39, 0xf8, 0x4d, 0xcf, 0x6b,
	0x8c, 0x0d, 0xf9, 0xef, 0x7c, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x39, 0x13, 0x00, 0xc7, 0xad,
	0x07, 0x00, 0x00,
}
